###

POST http://localhost:4000/users/register
Content-Type: application/json

{
    "fullname": {
        "firstname": "test_firstname",
        "lastname": "test_lastname"
    },
    "email": "test@test.com",
    "password": "test_password"
}

###

POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test_password"
}