###

POST http://localhost:4000/users/register
Content-Type: application/json

{
    "fullname": {
        "firstname": "test_firstname",
        "lastname": "test_lastname"
    },
    "email": "test@test.com",
    "password": "test_password"
}

###

POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test_password"
}

###

GET http://localhost:4000/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTdlNDdkNDdiYzJjYWJiNzNjNDU4YWIiLCJpYXQiOjE3NzAyMjgxMDV9.3WyD-Y0tVJUZfJH2Tr1pi5vQ65k1oOE1ZxAZqeopsks

###

GET http://localhost:4000/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTdlNDdkNDdiYzJjYWJiNzNjNDU4YWIiLCJpYXQiOjE3NzAyMjgxMDV9.3WyD-Y0tVJUZfJH2Tr1pi5vQ65k1oOE1ZxAZqeopsks

###

POST http://localhost:4000/captian/register
Content-Type: application/json

{
    "fullname": {
        "firstname": "test_captian_firstname",
        "lastname": "test_captian_lastname"
    },
    "email": "test_capt@tsaddsa.com",
    "password": "test_captian",
    "vechile": {
        "color": "red",
        "plate": "HR 26 FS 8155",
        "capacity": 2,
        "vechileType": "motorcycle"
    }
}

###

POST http://localhost:4000/captian/login
Content-Type: application/json

{
    "email": "test_capt@tsaddsa.com",
    "password": "test_captian"
}

###

GET http://localhost:4000/captian/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTg0NmE3MTM1ZjYxZDFkYzNlYzA0ZGQiLCJpYXQiOjE3NzAyODg5ODksImV4cCI6MTc3MDM3NTM4OX0.e89nAy6g7rOuBsejC13eod_LfoZoSXjOXJEc-uKXUfI

###

GET http://localhost:4000/captian/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTg0NmE3MTM1ZjYxZDFkYzNlYzA0ZGQiLCJpYXQiOjE3NzAyODg5ODksImV4cCI6MTc3MDM3NTM4OX0.e89nAy6g7rOuBsejC13eod_LfoZoSXjOXJEc-uKXUfI
